# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

version: '3.7'

# Define services
services:
  # App backend service
  self-request-service:
    build:
      context: .
    # Configuration for building the docker image for the backend service
    image: self-request-docker # Use an image built from the specified dockerfile in the `polling-app-server` directory.
    ports:
      - "8085:8085" # Forward the exposed port 8085 on the container to port 8085 on the host machine
    restart: always
    depends_on: 
      - db # This service depends on mysql. Start that first.
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
      - frontend


  # Database Service (Mysql)
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: self_request
      MYSQL_USER: root
      MYSQL_PASSWORD: abc123
      MYSQL_ROOT_PASSWORD: abc123
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - 8000:80
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: abc123
      MYSQL_ROOT_PASSWORD: abc123
    networks:
      - backend

  frontend:
    build:
      context: ./frontend/self-request-frontend/
    image: frontend:latest
    volumes:
      - '.:/frontend/self-request-frontend/app'
      - './frontend/self-request-frontend/app/node_modules'
    networks:
      - frontend
    ports:
      - "3000:3000"

# Volumes
volumes:
  db-data:

# Networks to be created to facilitate communication between containers
networks:
  backend:
  frontend:    