name: IPM Project CI

on:
  push:
    branches: [ master, automation ]    
    tags:
      - v*


jobs:

  ipm-internship-project-deployment:
    runs-on: self-hosted
    steps:      
      - uses: actions/checkout@v2      
      - name: Verify microservices configuration
        working-directory: ./automation/ipm-project
        run: >             
            cat 
            docker-compose.yml 
            docker-compose-networks.yml 
            docker-compose-volumes.yml 
            docker-compose-il-*.yml 
            docker-compose-app-*.yml 
            docker-compose-services.yml 
            > deploy.yml | 
            docker-compose -f deploy.yml config    
      - name: Build docker images
        working-directory: ./automation/ipm-project
        run: echo $(pwd) && echo $(ls -1) && docker-compose -f deploy.yml build
      - name: Let the Magic begin
        working-directory: ./automation/ipm-project
        run: docker-compose -f deploy.yml up -d
  
